// components/ExperienceItem.vue
<template>
  <section :class="{ 'u-print-hidden': shouldHideFromPrint }" class="ExperienceItem">
    <header>
      <div class="period">
        {{ content.start.month }} {{ content.start.year }} - {{ content.end.month }} {{ content.end.year }}
        <span v-if="content.location" class="location">({{ content.location }})</span>
      </div>
      <h3 v-if="content.name" class="name">
        {{ content.name }}
        <span v-if="content.isDefunct" class="defunct">(defunct)</span>
      </h3>
      <div class="role">
        {{ content.role }}
        <span v-if="content.isContractor" class="type">Contractor</span>
      </div>
    </header>
    <div
      v-if="content.description"
      class="description"
      v-html="$md.render(content.description)"
    />
    <ListSection
      v-if="content.technologies"
      :items="content.technologies"
      inline
      class="technologies"
      title="Technologies & tools:"
    />
  </section>
</template>

<script>
import ListSection from './ListSection';

export default {
  components: {
    ListSection,
  },
  props: {
    content: {
      type: Object,
      default: () => {},
    },
  },
  computed: {
    shouldHideFromPrint() {
      const itemStartYear = parseInt(this.content.start.year, 10);
      const threeYearsAgo = new Date().getFullYear() - 4;
      return itemStartYear < threeYearsAgo;
    },
  },
};
</script>

<style scoped>
@import '~/css/_settings.css';

.ExperienceItem {
  page-break-inside: avoid;
  max-width: 70ch;

  @nest .ExperienceItem + & {
    margin-top: 2em;

    &::before {
      content: '';
      border-top: 0.25em solid var(--color-blue-500);
      opacity: 0.5;
      margin-bottom: 2em;
      width: 3em;
      display: block;
    }
  }

  & > * + * {
    margin-top: 1em;
  }
}

.name {
  margin: 0;
  font-size: 1.25em;
}

.name .defunct {
  margin-left: 0.25em;
  font-weight: 300;
  color: #aaa;
  font-size: 1rem;
}

.period,
.role {
  margin: 0;
  font-size: 0.9em;
}

.role {
  color: #666;
}

.type {
  font-size: 0.8em;
  font-weight: 500;
  display: inline-block;
  padding: 0.1em 0.3em 0;
  text-transform: uppercase;
  border-radius: 0.2em;
  background-color: #eee;
  margin-left: 0.2em;
}

.technologies {
  font-size: 0.9em;
}

@media print {
  .type {
    color: #aaa;
    border: 1px solid #ccc;
    background-color: transparent;
  }

  .ExperienceItem + .ExperienceItem::before {
    border-color: #000;
  }

  .u-print-hidden + .technologies {
    margin-top: 10px;
  }
}
</style>

// src/lib/ExperienceItem.svelte
<script>
  import List from './List';
  import { periodDuration } from '../utils';

  const PRINT_TRUNCATE_NUMBER_OF_YEARS = 4;

  function shouldHideFromPrint() {
    const itemStartYear = parseInt(end.year);
    const yearsAgo = new Date().getFullYear() - PRINT_TRUNCATE_NUMBER_OF_YEARS;
    return itemStartYear < yearsAgo;
  }

  export let name;
  export let description = null;
  export let start = {};
  export let end = {};
  export let location = null;
  export let role = '';
  export let isDefunct = false;
  export let isContractor = false;
  export let technologies = [];

  const duration = periodDuration(start, end);
</script>

<div class="experience-item" class:u-print-hidden={shouldHideFromPrint()}>
  <header>
    <div class="period">
      {start.month}
      {start.year} -
      {#if end.year}{end.month} {end.year}{:else}present{/if}
      {#if duration}
        <span class="duration">({duration})</span>
      {/if}
      {#if location}
        <span class="location">({location})</span>
      {/if}
    </div>
    <h3 class="name">
      {name}
      {#if isDefunct}
        <span class="defunct">(defunct)</span>
      {/if}
    </h3>
    <div class="role">
      {role}
      {#if isContractor}
        <span class="type">Contract</span>
      {/if}
    </div>
  </header>
  {#if description}
    <div class="description">
      {@html description}
    </div>
  {/if}
  {#if technologies.length}
    <footer>
      <h4>Technologies & tools</h4>
      <List items={technologies} inline />
    </footer>
  {/if}
</div>

<style lang="postcss">
  .experience-item {
    page-break-inside: avoid;

    & > * + * {
      @apply mt-4;
    }
  }

  header > * + * {
    @apply mt-1;
  }

  .name {
    @apply font-bold leading-tight;
    font-size: 1.25em;
  }

  .period,
  .role {
    font-size: 0.95em;
  }

  .period {
    @apply font-medium;
  }

  .role,
  .duration {
    @apply text-gray-500;
  }

  .type {
    @apply inline align-middle font-bold uppercase p-1 rounded bg-blue-50 text-blue-900;
    font-size: 0.8rem;
  }

  footer {
    font-size: 0.85em;
  }

  h4 {
    @apply font-bold;
  }

  @media screen {
    :global(.experience-item.visible)::before {
      @apply text-blue-900 opacity-100;
    }
  }

  @media print {
    .type {
      @apply text-gray-500 border bg-white;
      font-size: 7pt;
      margin-left: 2pt;
    }
  }
</style>
